### ISSUE TITLE
There are some bugs in your code. 

### ISSUE THREAD

**Issue by BravoLu** [whj363636/Adversarial-attack-on-Person-ReID-With-Deep-Mis-Ranking#1]
When I run your code Pytorch 1.0, I find some bugs. 
e.g., 
In line 23 in train.py:  from ReID_attr import get_target_withattr
In line 66 in advloss.py: smooth[pids.data.cpu()] = 0
In line 1183 in data_manager.py: return __img_factory.keys() + __vid_factory.keys()
in line 386 in train.py: delta[i,ci,:,:].data *= np.minimum(1.0, mag_in_scaled_c / l_inf_channel).float().cuda()

And I make some revision to fix it. 
In line 23 in train.py: # from ReID_attr import get_target_withattr
In line 66 in advloss.py: smooth[:, pids.data.cpu()] = 0
In line 1183 in data_manager.py: return list(__img_factory.keys()) + list(__vid_factory.keys())
in line 386 in train.py: delta[i,ci,:,:].data *= np.minimum(1.0, mag_in_scaled_c / l_inf_channel.cpu()).float().cuda()

**Comment by whj363636** [comment]
I add some annotations and update the readme. Thanks for your revision on Pytorch 1.0.
