### ISSUE TITLE
对抗样本

### ISSUE THREAD

**Issue by finger-monkey** [whj363636/Adversarial-attack-on-Person-ReID-With-Deep-Mis-Ranking#10]
可以向您要一下Market和DUKE数据集的对抗样本吗？我在尝试获取DUKE数据集对抗样本时，程序上遇到了一堆版本问题解决不来。恳请你们能够分享一下所生成的对抗样本。

**Comment by whj363636** [comment]
Have already replied to the e-mail 19 days ago. But right now I'm busy applying for my Ph.D. program and preparing some required exams. I will keep this issue open. It would be grateful if someone who runs the code and fix the issue conveniently.

**Comment by finger-monkey** [comment]
请问用你们的代码训练出来的对抗样本是这样的
![image](https://user-images.githubusercontent.com/52326609/97769114-2ddb6f80-1b63-11eb-9610-abef78acfb2a.png)
这是正常的结果吗

**Comment by whj363636** [comment]
已经邮件回复了该issue的问题，为了节约后面朋友的时间，贴上我的回复内容：

网格状噪声是正常的（或者说，论文方法生成的对抗噪声的特性就是会带网格状，在论文中的所有图表里也没有掩饰这一点），但严重程度没有上述样本这么高，因为我做了一些小微调：
1. 不取第50代的样本。在训练时其实不需要完全训练到50代，就可以达到比较好的效果了。
2. 在不影响性能的情况下，略微调高了ms-ssim的权重，但相对于release的版本比较难balance性能和可视化，需要多次随机化训练获得最好的那个。

关于消除网格的问题，后续有兴趣跟进工作的朋友可以作为改进的点。另外，附上其他攻击方法在该任务上的表现，作为我们工作可视化水平的参考（与文中Fig4一样，为eps=50）
![polluted_epochtest_batch94](https://user-images.githubusercontent.com/8454140/97769941-e3a9bc80-1b69-11eb-90e4-6615cdf2d6be.png)
![polluted_epochtest_batch95](https://user-images.githubusercontent.com/8454140/97769943-e5738000-1b69-11eb-8e6e-d90c75822554.png)
![polluted_epochtest_batch96](https://user-images.githubusercontent.com/8454140/97769944-e73d4380-1b69-11eb-80e9-73dbbdbac620.png)

**Comment by BravoLu** [comment]
> 请问用你们的代码训练出来的对抗样本是这样的（脸部颜色失真，并有网格状噪声）
> ![image](https://user-images.githubusercontent.com/52326609/97769151-798e1900-1b63-11eb-9a68-e425916b3979.png)
> 
> 这是正常的结果吗

我试过用随机噪声也是这种偏绿的结果，而且攻击成功率也基本一致。
