### ISSUE TITLE
Black box attack

### ISSUE THREAD

**Issue by htyj123** [whj363636/Adversarial-attack-on-Person-ReID-With-Deep-Mis-Ranking#11]
hello, I want to know that whether I need to take some measures on other datasets when I want to do the Cross-dataset attack like drop some classes . I notice that the number of class in the training dataset is different from others. This measure whether cause the drop of accuracy. Please help me!!

**Comment by whj363636** [comment]
Not necessary. I do not guarantee whether dropping some classes will increase the accuracy, but it will not cause accuracy drops during the Cross-dataset attack experiment. Hope this will help you:)
