### ISSUE TITLE
运行时出错，我是直接下载的完整代码，但是在运行时出现如下错误：

### ISSUE THREAD

**Issue by PhilChina** [whj363636/Adversarial-attack-on-Person-ReID-With-Deep-Mis-Ranking#13]
Traceback (most recent call last):
  File "train.py", line 494, in <module>
    main(opt)
  File "train.py", line 140, in main
    target_net = models.init_model(name=args.targetmodel, pre_dir=pre_dir, num_classes=dataset.num_train_pids)
  File "/Eric/works/Adversarial-attack-on-Person-ReID-With-Deep-Mis-Ranking/models/__init__.py", line 41, in init_model
    checkpoint = torch.load(pre_dir)
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 542, in _load
    result = unpickler.load()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa8 in position 0: ordinal not in range(128)

**Comment by PhilChina** [comment]
python 3.6.9
torch == 0.4.1
ubuntu  16.04
cuda 10.2

**Comment by PhilChina** [comment]
./models/__init__.py 文件代码作如下修改：
# checkpoint = torch.load(pre_dir)  修改为

from functools import partial
import pickle

pickle.load = partial(pickle.load, encoding="latin1")
pickle.Unpickler = partial(pickle.Unpickler, encoding="latin1")
checkpoint = torch.load(pre_dir, map_location=lambda storage, loc: storage, pickle_module=pickle)

应该可以解决这个问题(也是在别的地方看到的解决办法，确实有效，这里贴一下，如果有别的小伙伴遇到同样的问题可以尝试一下。

**Comment by PhilChina** [comment]
方法二
直接修改
checkpoint = torch.load(pre_dir, encoding="latin1")

**Comment by whj363636** [comment]
In fact, the essence of this issue is that the model was pretrained and saved in Python2.7 but reload in Python3+. So the perfect configuration for this project is python 2.7 + Pytorch 0.4.0. I will add some comments for that. Thanks for your enthusiasm!
