### ISSUE TITLE
Would D leak knowledge to G

### ISSUE THREAD

**Issue by Chenfeng1271** [whj363636/Adversarial-attack-on-Person-ReID-With-Deep-Mis-Ranking#14]
Dear Sir:
Thanks for your elegant work. But I still have some questions about the paper.  In the flow of attack generation, I saw the mask is generated by D and then multiplied by noise from G.  However, the GAN paradigm is in the outer supervision. Would this design leak discriminator knowledge to the generator? As you know, in the competition between G and D, once either G or D know its opponent's knowledge，only two results would happen 1 the knowledge is soon abandoned 2 the competition would collapse.  I know KeepTopK to some extent is to avoid this catastrophe, but I think the visualization shows it doesn't make sense. 

If I misunderstand it, please correct my understanding. Thanks.
![image](https://user-images.githubusercontent.com/24824628/127254734-e072ef13-76cd-402d-9a38-012c10b64fbe.png)

**Comment by whj363636** [comment]
Sorry, it seems that your question lay the keys to itself already so I don't get the point. I guess you want to improve the way to find more aggressive adversarial pixels or find some insights about the layout of themselves. For the former, although the performance of our method is good, it still has space to be modified including the issues you gave. For the latter, I hope Figure 5 in the paper might give you some help.

**Comment by Chenfeng1271** [comment]
Thanks for your reply. I recently do some experiments on this and find how to avoid knowledge disturbance is useful. Besides, I am curious about using attribute supervision to guide attacks. This generation is similar to the text-guided image synthesis, such as [1] but still something different. Can you give me some paper references to explore this idea in Reid.

[1] Zhou X, Huang S, Li B, et al. Text guided person image synthesis[C]//Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition. 2019: 3663-3672.

**Comment by whj363636** [comment]
Tbh, it is a little beyond the duty of this repository. But I read some papers[1][2] before, which may be related to what you said and cited. Hope these help.

[1] Men, Yifang, et al. "Controllable person image synthesis with attribute-decomposed gan." Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition. 2020.
[2] Yin, Zhou, et al. "Adversarial attribute-image person re-identification." arXiv preprint arXiv:1712.01493 (2017).
