### ISSUE TITLE
Could ReID system be attacked by digital attack?

### ISSUE THREAD

**Issue by fiona-lxd** [whj363636/Adversarial-attack-on-Person-ReID-With-Deep-Mis-Ranking#5]
Thanks for your contribution. In my opinion, there's little chance that someone is available to make digital attacks on captured photos. This algorithm can be used to attack other image retrieval systems like google or baidu. So, I'm wondering if you have tried to attack some other image retrieval tasks such as oxford building searching or datasets like CUB2011 etc.

**Comment by whj363636** [comment]
You're right. It is impractical to make attacks on captured photos directly. But the motivation of our paper is to examine the robustness of ReID systems and to engage the community in designing a more robust ReID system, which is crucial for the applications with security-sensitive purposes. The real-world attack (like https://www.cs.cmu.edu/~sbhagava/papers/face-rec-ccs16.pdf) is indeed an important and potential direction of our work, but a good (transferable/controllable/inconspicuous) generation of adversarial perturbation is always the first task :). 

As for other image retrieval tasks, we did perform an attack on Baidu APIs for Human Detection and Attributes but did not conduct experiments on Oxford building or CUB2011 datasets. But we believe that the algorithm is suitable for any problem which can be considered as / converted to a ranking problem.

**Comment by fiona-lxd** [comment]
Thank you for your reply. I'll have a try with it on other image retrieval tasks.

**Comment by whj363636** [comment]
OK. I will temporarily close the issue. Feel free to re-open it whenever something big happens :).
