### ISSUE TITLE
Some question about the mask 

### ISSUE THREAD

**Issue by BravoLu** [whj363636/Adversarial-attack-on-Person-ReID-With-Deep-Mis-Ranking#6]
I directly run you code following the instructions, and get the mask result like this
![image](https://user-images.githubusercontent.com/28304030/85243788-55b01d80-b475-11ea-95bd-94808cbc6822.png)
It shows that the mask do not work , or are there some bugs in your code?

**Comment by whj363636** [comment]
No. If directly running the code, what you have performed is the full-size attack (as shown in your figure), which corresponds to our main experiments (Table.1) in our paper. If you want to control the number of attack pixels, please modify the hyper-parameter 'temperature' (the default setting is -1, which means attacking all the pixels on the image). You can set whatever number you want as long as it doesn't exceed the limit. Also, to get better performance, I recommend smoothly decrease the temperature.

**Comment by BravoLu** [comment]
I can not find the temperature value in your paper? Could you tell me the value of temperature you set in your paper? Or just tell me the suitable value.

**Comment by whj363636** [comment]
We use the symbol **tau** (Eq.2 in the paper) to represent temperature. And I will modify the helper of temperature to avoid the confusion. 

If you only want to verify the results in the paper, you just follow the default hyper-parameters and ignore my above suggestion. So you don't necessarily worry about the value of temperature. The temperature is not an adaptive parameter and only relevant to the number of adversarial pixels. For example, you'll set the temperature as 8208 when you want to attack a quarter of the pixels in a given 288x144 image.
