### ISSUE TITLE
Feature Extraction

### ISSUE THREAD

**Issue by kuihua** [whj363636/Adversarial-attack-on-Person-ReID-With-Deep-Mis-Ranking#7]
Hi! 
Can you show me the cooresponding feature length extracted by all these Re-id models on these test datasets (Market1501, cuhk03, and duke). 
Whether the extracted feature has the same length with that of the original paper.
Look forward your help!

**Comment by whj363636** [comment]
Not all, like PCB, I resized the input image to 384x192 for better Rank-1 and mAP (more details about other models please refer to opt.py)

It seems I have replied to your e-mail asking about the same question five days ago, so I close the issue. :)
