### ISSUE TITLE
We are doing defense based on your code, but we don't know exactly how to customize our model

### ISSUE THREAD

**Issue by finger-monkey** [whj363636/Adversarial-attack-on-Person-ReID-With-Deep-Mis-Ranking#8]
我发现你们的工作迁移能力很强！很厉害的一项工作。我们正在基于你们的代码在做防御方面的工作，但是我们不是很清楚到底该如何定制自己的模型，不知道您的代码之后会不会支持CVPR2019的reid-strong baseline?他的github链接如下：
https://github.com/michuanhaohao/reid-strong-baseline.
还有能否发布你们的被攻击模型-PCB的训练代码？以便于我们能够改造，更方便地开展防御工作。

**Comment by finger-monkey** [comment]
在定制模型时，所使用的权重文件.pth好像会依赖于原来被攻击模型代码的目录结构，从而引发一些麻烦。

**Comment by whj363636** [comment]
感谢关注。

reid-strong baseline的工作确实很优秀，但暂时没有与其整合的计划。

关于PCB，我只针对PCB的输入大小做了改动（参见opts.py），其他部分与原论文一致，PCB的网络结构可以在models文件夹下找到，我想应该还是比较容易复现的。

关于定制模型可参考readme中Prepare pretrained ReID models小节的两处optional选项。若需要攻击自定义reid模型：（1）设计网络结构并放到models文件夹下。（2）在__init__.py文件中注册结构的文件名，并根据自己需要修改Line 38–53，以解决resume时前缀的问题（这里的前缀问题指DataParallel的跨版本问题，因为当初我pretrain模型时环境是pytorch0.3，后来服务器迁移后的运行环境是0.4，目前用1.0+的话可以需要做调整）。（3）把预训练好的权重文件按模型名建立自己的文件，也放在models下，详情可参考同节downlinks章的pretrained模型的命名方式。我猜所谓的依赖目录结构目测是train.py中Line80-82的路径拓展？如果按上述推荐方式放置自定义模型，直接运行train文件是会自动定位到models下的同名模型文件夹下的.pth文件的，如果想自定义位置，可以考虑删除上述行并自己在命令行参数中指定路径。
